# Welcome to Jekyll!
#

# Site settings
title: OF10 Labs
description: |
  A new age branding and web agency
owner: OF10
first_published: 2016 # if migrating another site, the year of your first publish
email: labs@of10.in
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://labs.of10.in" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/of10labs
  github: https://github.com/of10labs
  linkedin-square: https://linkedin.com/in/of10labs
  facebook-official: https://facebook.com/of10labs
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
